### ISSUE TITLE
Fitting form into single screen

### ISSUE THREAD

**Issue by schajee** [codeforpakistan/Disability-Certificate---One-Window-Operation#2]
I know this is not a best practice, but can we try and fit the form in to a single page (i.e. without scroll). I feel as a data entry operator, I would be more comfortable seeing all the information I've entered, without scrolling. 

**Rationale**
- The screens will be limited to maybe 1080p; there is plenty of real estate to play with
- DEOs prefer to use keyboard vs mouse because its faster when you get used to the keyboard
- Viewing the whole process and data allows DEOs to identify errors and omissions in a glance

**Comment by mubassirhayat** [comment]
Form inputs moved to two columns.
