### ISSUE TITLE
Editing option after submission

### ISSUE THREAD

**Issue by ebtihaj-khan** [codeforpakistan/Disability-Certificate---One-Window-Operation#22]
There can be a case where the staff submits incorrect data and wants to edit it again.

**Comment by ebtihaj-khan** [comment]
#24

**Comment by ebtihaj-khan** [comment]
Add comments and submit for reverification

**Comment by ebtihaj-khan** [comment]
@laraibsahmed need to finalize a cutoff point for editing an application. Can possibly be after the generation of a certificate?

**Comment by laraibsahmed** [comment]
once the application goes to board member, It shouldn't be updated/edited. 
FYI - @ebtihaj-khan @mubassirhayat @aliirz

**Comment by mubassirhayat** [comment]
duplicate of #59
