### ISSUE TITLE
We need to list down all created applicant profiles other than the option to search them.

### ISSUE THREAD

**Issue by laraibsahmed** [codeforpakistan/Disability-Certificate---One-Window-Operation#30]
Please let me know if its already in place, otherwise we need to have an option on search screen that leads us to listing of created applicants.

**Comment by mubassirhayat** [comment]
Already implemented. Each user will have a list of applications that are in progress and need their attention.

**Comment by ebtihaj-khan** [comment]
@mubassirhayat need a complete list and view for a super admin.

**Comment by mubassirhayat** [comment]
@ebtihaj-khan please add this to sprint 2

**Comment by mubassirhayat** [comment]
provided in #52
