### ISSUE TITLE
Date format is taking more number digits in year than 4, attached screenshot for reference

### ISSUE THREAD

**Issue by laraibsahmed** [codeforpakistan/Disability-Certificate---One-Window-Operation#31]
<img width="1440" alt="Screenshot 2021-05-25 at 2 22 18 PM" src="https://user-images.githubusercontent.com/83450157/119475290-74462500-bd66-11eb-8dc2-0acc83f6f5d8.png">

**Comment by mubassirhayat** [comment]
Validation is applied to this field already. You can write the year in this format but the application won't accept it when you submit the form/
