### ISSUE TITLE
PDF file not uploading - screenshot attached

### ISSUE THREAD

**Issue by laraibsahmed** [codeforpakistan/Disability-Certificate---One-Window-Operation#34]
<img width="1440" alt="Screenshot 2021-05-26 at 2 30 20 PM" src="https://user-images.githubusercontent.com/83450157/119637316-f9950c80-be2e-11eb-8fa2-f05e63542e5d.png">

This PDF file is only 3 MB in size

**Comment by mubassirhayat** [comment]
The maximum file size is now 32 MB. @schajee do we need to limit it to some lower size?
