### ISSUE TITLE
Long file names are causing file thumbnails to appear bigger than others - screenshot attached

### ISSUE THREAD

**Issue by laraibsahmed** [codeforpakistan/Disability-Certificate---One-Window-Operation#35]
<img width="1440" alt="Screenshot 2021-05-26 at 4 17 22 PM" src="https://user-images.githubusercontent.com/83450157/119651064-02d9a580-be3e-11eb-8bd8-4e0b3975c152.png">

**Comment by schajee** [comment]
@mubassirhayat When you have file types, replace name with type, and internally uses UUIDs to rename each file.
