### ISSUE TITLE
Doctor's name clears when user clicks on 'Submit' button without adding clinical findings - screenshot attached

### ISSUE THREAD

**Issue by laraibsahmed** [codeforpakistan/Disability-Certificate---One-Window-Operation#37]
<img width="1440" alt="Screenshot 2021-05-26 at 4 31 28 PM" src="https://user-images.githubusercontent.com/83450157/119652771-f48c8900-be3f-11eb-8e5e-3f09f77ab16d.png">

**Comment by ebtihaj-khan** [comment]
@mubassirhayat need to add old() here as well.
