### ISSUE TITLE
UI: Application assessment form

### ISSUE THREAD

**Issue by schajee** [codeforpakistan/Disability-Certificate---One-Window-Operation#62]
When logged in as Assessment...

Too much wasted space when assessing application. Screen can be split in two...

- [ ] LEFT = Applicant / Application data
- [ ] RIGHT = Assessment Form

Information presentation of Applicant Data is also bad, 

- [x] Use a Definition list or vertical table to organize the information.

**Comment by schajee** [comment]
- [ ] Shouldn't Doctor's name be Authenticated User's name?

**Comment by schajee** [comment]
- [ ] Checkbox labels are not usable (use IDs and FOR)

**Comment by ebtihaj-khan** [comment]
@mubassirhayat list of departments. 
Orthopedic Surgeon
Deputy Director (Council)
ENT Specialist (NIRM)
Eye Specialist (NIRM)
Audiologist (DGSE)

**Comment by mubassirhayat** [comment]
Shifted to a better view for the applicants data.
