### ISSUE TITLE
Applicant access to disability certificate

### ISSUE THREAD

**Issue by schajee** [codeforpakistan/Disability-Certificate---One-Window-Operation#66]
When a certificate is issued, it should be accessible via a URL for verification of printed matter. 

Multiple URLs will probably be needed. 

- [x] CRPD to view certificate `GET /admin/applications/:uuid/certificate`
- [x] Public to view non-printable certificate `GET /certificates/:cnic` (throttled)

**Comment by ebtihaj-khan** [comment]
@laraibsahmed would this be something that should be included in the scope of the project?

**Comment by laraibsahmed** [comment]
Yes this is required. @ebtihaj-khan @aliirz @mubassirhayat
