### ISSUE TITLE
UI: Create new application

### ISSUE THREAD

**Issue by schajee** [codeforpakistan/Disability-Certificate---One-Window-Operation#69]
- [x] Remove full stops after labels, unless required
- [x] Right-align label with textbox
- [x] Vertical center label with textbox
- [x] Standardize button color and label (see #57)
- [x] Use dropdowns where possible
- [x] Applicant is NOT a patient... should be APPLICANT NAME
- [x] Use Single, Married, Divorced, Widowed as marital status

**Comment by schajee** [comment]
- What if applicant has multiple disabilities? Can we separate disabilities into a separate model?
- What is the difference between TYPE and NATURE of disability?
- What if the applicant can only not do ONE type of job? Shouldn't this field be about what they cannot do?
- What if an applicant has multiple sources of income?

**Comment by ebtihaj-khan** [comment]
@laraibsahmed can you please answer question#1 and question#4?

**Comment by laraibsahmed** [comment]
I will discuss and confirm point 1 and 4 with Director CRPD
FYI - @ebtihaj-khan @aliirz @mubassirhayat
