### ISSUE TITLE
Adding a user for NADRA 

### ISSUE THREAD

**Issue by ebtihaj-khan** [codeforpakistan/Disability-Certificate---One-Window-Operation#80]
Need to add a user for NADRA officials. 

@laraibsahmed please share the functionality that needs to be provided to the NADRA user.

**Comment by laraibsahmed** [comment]
I spoke to PM Projects NADRA, he said there wont be any need for it since the application will be CNIC centric therefore their official will only receive CNIC number of applicant through API call and would process application for SCNIC using their own system.

**Comment by ebtihaj-khan** [comment]
Thanks @laraibsahmed, closing this issue.
