### ISSUE TITLE
Fix login screen / UI

### ISSUE THREAD

**Issue by ebtihaj-khan** [codeforpakistan/Disability-Certificate---One-Window-Operation#83]

**Comment by ebtihaj-khan** [comment]
<img width="1440" alt="Screenshot 2021-07-09 at 12 27 00 PM" src="https://user-images.githubusercontent.com/6501341/125040507-2d5f8500-e0b1-11eb-96f3-6c347de0b47b.png">

**Comment by aliirz** [comment]
@ebtihaj-khan  what's the error? I am not able to reproduce

**Comment by ebtihaj-khan** [comment]
Not an error, but the white space at the bottom of the screen
